### ISSUE TITLE
Overlaps volume control

### ISSUE THREAD

**Issue by chrisdlc119** [TheAndroidMaster/Status#27]
A similar problem to the solved overlaps heads-up notifications. The problem exists in an LG G4, don't know what about other devices.

**Comment by ArtyomIsFlash** [comment]
On ASUS ZenFone 2 ZE500CL with an ASUS ZenUI, the status bar just disappears when changing the volume and does return only after switching to another app.

**Comment by TheAndroidMaster** [comment]
Possible explanation for @ArtyomIsFlash - The only place the status bar identifies fullscreen apps is [here](https://github.com/TheAndroidMaster/Status/blob/master/app/src/main/java/com/james/status/services/StatusService.java#L213). I'm not sure if the volume controls are shown as fullscreen but they at least overlap the status bar in some way (transparent background?), causing it to go into fullscreen mode. Then when it's dismissed, [this line](https://github.com/TheAndroidMaster/Status/blob/master/app/src/main/java/com/james/status/services/AccessibilityService.java#L151) throws an exception (or the window change just isn't detected for some reason), so the status bar doesn't reset. Might be able to fix it by checking for the systemui package name before entering fullscreen mode, but I'm not sure how I would re-organize the services to allow that.

As for the original issue, I still have no clue what's happening. Hopefully I'll be able to fix it eventually :P

**Comment by TheAndroidMaster** [comment]
Fixed this by basically listening for either the volume changed broadcast action (which is also sent when the volume panel is opened, not just when the volume is changed) and also listening for the word 'volume' in an accessibility event. 

Since the broadcast action only works on Lollipop, I've had to rely solely on accessibility events for Marshmallow and Nougat. On some devices (mostly Nougat) it sends two accessibility events, one when it opens and one when it closes. The issue @ArtyomIsFlash had was most likely that it read both the issues as the panel opening - I've prevented this from happening by checking for the word 'hidden' as well, which is present in the second event. On Marshmallow, only the first event is sent, so I set a delay for the status bar to show itself again whenever the accessibility event is received. This may cause an issue since the delay for the panel to hide can vary based on the manufacturer, but it shouldn't be too annoying.

Since the volume changed broadcast works on Lollipop I simply listen for the broadcast then set a delay for the status bar to show itself, the same as on Marshmallow (except it's slightly more accurate because it also detects when the volume is changed, not just when the panel is opened). Below Lollipop it's not possible for the panel to overlap the status bar, so the majority of this issue has been fixed. There may be a few issues with devices running heavily modified versions of android, since the text in the accessibility event can be modified, but it works fine on my HTC and as far as I can tell the text doesn't change if the default language isn't set to English,, so it should be fine.
