### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by IzzySoft** [TheAndroidMaster/Status#36]
You might not be aware of it, but the last two versions are throwing malware alerts:

* [version 2.7](https://www.virustotal.com/de/file/9f2fdadd86eaa57b1fb93cfcef6b8055d5435786c398713859ae1fd541b63679/analysis/1479156281/): Spyware/Virtumonde reported by Panda
* [version 2.8](https://www.virustotal.com/de/file/bfbcdb5c40c2d026780ea5a0db4def35b62c5822aa4fb7293b1baea737aab8d9/analysis/1479164638/): Spyware/Virtumonde reported by Panda

v2.6 was reported clean. Not sure what caused that, or what to do about it – but I thought to at least let you know.

**Comment by TheAndroidMaster** [comment]
Antivirus on android is for the most part obsolete, since most just read the permissions the app uses, how many services it has, and other details in the manifest. It might be possible to detect 'malicious' activity by decompiling the app and parsing the java files, or they could just use a massive amount of reflection, but I still doubt its accuracy. The app most likely just got flagged because of the amount of permissions it has. Nothing significant (except for the handling of icon styles and a few design tweaks) has been changed between 2.6 and 2.8 - for the most part the main sections the app have stayed the same.

Conclusion: Status does not contain adware, analytics, or anything even remotely malicious. If anyone claims it is a virus I will direct them to this repo - there is more than one reason I keep projects open source.

**Comment by IzzySoft** [comment]
@TheAndroidMaster you understood me wrongly: I don't have any such useless AV app on any of my devices. But I use an external service (VirusTotal) to check APKs (see the links), plus LibRadar for contained libraries.

And no, I definitely did ***NOT*** accuse you of including anything malicious!!! As it's only 1 of 55 scanners throwing the alert, I'd rather consider that a "false positive".

So full ack on your OpenSource understanding, and I'm fully with you! As I wrote initially, I just wanted to let you know. 

> Status does not contain adware, analytics, or anything even remotely malicious. If anyone claims it is a virus I will direct them to this repo - there is more than one reason I keep projects open source.

Bold and underline that. Consider the issue past then :) Thanks a lot, especially for your fast response and your stance. Really appreciated! Btw: proof of my appreciation (and background of my findings) is [this page](https://apt.izzysoft.de/fdroid/index/apk/com.james.status) – helping out open-source-minded people who abandoned GPlay or cannot access it for other reasons.

**Comment by IzzySoft** [comment]
As version 2.9 still gets the same reports (which might confuse some people – and that's the only reason I'm updating this issue): Any idea what could be triggering that false alert? After all, the claimed infection is obviously not very believable if looked into closer (Virtumonde is a Windows `.dll` malware). So I'd rather remove all doubt by being able to show a "green shield" even though I know that one warning could be ignored.
