### ISSUE TITLE
Add more OS icons.

### ISSUE THREAD

**Issue by gofirst2220** [TheAndroidMaster/Status#41]
It seems like right now, it's full of generic non-Marshmallow icons for NFC, Location, Time and Bluetooth. Since I'm on Samsung Galaxy S6 on Android Marshmallow, there are some Touchwiz-only Status icons, others are Goggle's version.

**Comment by TheAndroidMaster** [comment]
The app has the ability to add custom icons if you don't like the preset ones. The Marshmallow icons are for the most part the same as Google's icons apart from the battery icon. If you have any icon sources you would like to share that are under the creative commons license or similar, please make a pull request to add them to this repository as illustrated in the readme. Otherwise, I cannot add icons from specific operating systems as it would infringe their copyright.
