### ISSUE TITLE
[Request] Detect color automatically

### ISSUE THREAD

**Issue by OussDeCouette** [TheAndroidMaster/Status#43]
The app is very good, but if you don't mind :
-It would be great if the app would detect the color of the app.
For example it scans the color of the last line of pixels (I don't know how it works but it's just an idea), and if the color is the same for each pixel of the line. it selects the color.
-And maybe update the color while we navigate on an app. I'm thinking mostly about messenger, to change the color depending on the contact.

**Comment by TheAndroidMaster** [comment]
This has been attempted before, it is possible but unusable due to lag and battery usage. This would effectively mean you're recording video the entire time the screen is turned on. Not only would it take up massive amounts of memory (Status already takes up enough, thanks :P ), it also takes a lot of power to keep it running.

The app already detects activity-specific colors using resources that are usually accurate. If that doesn't work, there's still an option to set colors manually. Other than this, there isn't anything more that can be done without root access.
